# Generated by Django 4.2.11 on 2024-11-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_likedislike_rename_blogs_comment_blog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
