# Generated by Django 4.2.11 on 2024-11-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='posts.blog'),
        ),
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together={('blog', 'user', 'comment')},
        ),
    ]
